In [9]:
%pip install nptyping


  Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)


# 1. Declaring Arrays

In [10]:
from nptyping import NDArray
import numpy as np
# from typing import Any

a : NDArray = np.array(1000)
a1D: NDArray = np.array([1, 2, 3, 4])
a2D: NDArray = np.array([[1, 2], [3, 4]])
a3D: NDArray = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(a)
print(a1D)
print(a2D)
print(a3D)

1000
[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# 2. np.inid()

In [12]:
def elements_in_array(arr1: NDArray, arr2: NDArray) -> NDArray:
    return np.in1d(arr1, arr2)

print(elements_in_array([1,2,4], [1,5,4]))

[ True False  True]


# 3. np.intersect1d()

In [14]:
def intersection_of_arrays(arr1: NDArray, arr2: NDArray) -> NDArray:
    return np.intersect1d(arr1, arr2)

print(intersection_of_arrays([1,2,4], [1,5,4]))

[1 4]


# 4. np.arange()

In [16]:
x: NDArray = np.arange(10)
print(x)
print(x[-3])
print(x[3])

[0 1 2 3 4 5 6 7 8 9]
7
3


# 5. np.cos()

In [28]:
x: NDArray = np.cos([0,np.pi,np.pi/4,np.pi/2])
print(x)
print(x[1])
print(x[-1])

[ 1.00000000e+00 -1.00000000e+00  7.07106781e-01  6.12323400e-17]
-1.0
6.123233995736766e-17


# 6. np.pi

In [31]:
a: float = np.pi
a

3.141592653589793

# 7. np.insert()

In [46]:
x = np.insert([0,1,2], 1,[5,6,7,8])
x

array([0, 5, 6, 7, 8, 1, 2])

# 8. np.array_str

In [50]:
b:str = np.array_str(x)
b

'[0 5 6 7 8 1 2]'

# 9. np.transpose

In [52]:
a: NDArray = [[3,4,5], [1,2,3]]
np.transpose(a)

array([[3, 1],
       [4, 2],
       [5, 3]])

# 10. np.split

In [54]:
x = np.arange(12)
np.split(x,6)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

# 11. np.repeat

In [58]:
print(np.repeat(3, 4))
x: NDArray = [[1,2],[3,4]]
print(np.repeat(x, 2))
x: NDArray = [[1,2,3,4,5,6]]
print(np.repeat(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]
[1 1 2 2 3 3 4 4 5 5 6 6]


### Codeforces Practice
This repository contains my solutions to various codeforces problems that I have solved as part of my daily practice. The problems are categorized by their difficulty level and topic, and some comments explaining my approach and logic.

### Problem Sets
The problems that I have solved are based on the following blog post that lists some basic problem sets for beginners and intermediate coders:


The problem sets are divided into 3 categoies as mntioned in listing from the codeforces blog:

## [Click Here](https://codeforces.com/blog/entry/82143)

The solutions are written in C++ and can be compiled and run using any C++ compiler. For example, to compile and run the solution to problem A of codeforces round 731, you can use the following commands:

```
g++ -std=c++17 file_name.cpp -o file_name
./file_name
```

Alternatively, you can use any online IDE or code editor that supports C++ to run the solutions. For example, you can use [replit] to run the solution to problem A of codeforces round 731 by copying and pasting the code [here].

Feedback and Suggestions
I welcome any feedback and suggestions on how to improve my solutions or my coding skills. You can contact me through my [codeforces profile](https://codeforces.com/profile/SheikhXAdil) or leave a comment on this repository. Thank you for visiting my repository and happy coding!